# typed: false
# frozen_string_literal: true

# Homebrew formula for Nesbot CLI
# Generated by scripts/generate-formula.sh — do not edit manually
#
# Install: brew install NesloTechnologies/nesbot/nesbot
# Upgrade: brew upgrade nesbot

class Nesbot < Formula
  desc "Deterministic, policy-driven engineering automation CLI"
  homepage "https://github.com/NesloTechnologies/nesbot"
  url "https://github.com/NesloTechnologies/homebrew-nesbot/releases/download/v1.31.21/nesbot-1.31.21-darwin-arm64.tar.gz"
  sha256 "1c23d2a4b22f2f39aad3b1f4726d8fed7687dca4f62a7c3fac9c97032e3fef71"
  version "1.31.21"
  license "MIT"

  def install
    libexec.install Dir["*"]

    # Create a wrapper script that invokes the CLI via the system node
    # Requires Node.js >= 18 (nvm, brew node, or system install)
    (bin/"nesbot").write <<~EOS
      #!/usr/bin/env bash
      exec node "#{libexec}/bin/nesbot.js" "$@"
    EOS
  end

  test do
    # Verify the CLI starts and can init a repo
    system bin/"nesbot", "init", "--repo", testpath/"test-repo"
    assert_predicate testpath/"test-repo/.nesbot/config.json", :exist?
  end
end
