# typed: false
# frozen_string_literal: true

# Homebrew formula for Nesbot CLI
# Generated by scripts/generate-formula.sh — do not edit manually
#
# Install: brew install NesloTechnologies/nesbot/nesbot
# Upgrade: brew upgrade nesbot

class Nesbot < Formula
  desc "Deterministic, policy-driven engineering automation CLI"
  homepage "https://github.com/NesloTechnologies/nesbot"
  url "https://github.com/NesloTechnologies/homebrew-nesbot/releases/download/v1.33.7/nesbot-1.33.7-darwin-arm64.tar.gz"
  sha256 "38e13ba44baa48d9df9fc94419b92a041826cc702b3649abd3cc31ab8f4aa977"
  version "1.33.7"
  license "MIT"

  def install
    libexec.install Dir["*"]

    # Create a wrapper script that invokes the CLI via the system node
    # Requires Node.js >= 18 (nvm, brew node, or system install)
    (bin/"nesbot").write <<~EOS
      #!/usr/bin/env bash
      exec node "#{libexec}/bin/nesbot.js" "$@"
    EOS
  end

  test do
    # Verify the CLI starts and can init a repo
    system bin/"nesbot", "init", "--repo", testpath/"test-repo"
    assert_predicate testpath/"test-repo/.nesbot/config.json", :exist?
  end
end
