# typed: false
# frozen_string_literal: true

# Homebrew formula for Nesbot CLI
# Generated by scripts/generate-formula.sh — do not edit manually
#
# Install: brew install NesloTechnologies/nesbot/nesbot
# Upgrade: brew upgrade nesbot

class Nesbot < Formula
  desc "Deterministic, policy-driven engineering automation CLI"
  homepage "https://github.com/NesloTechnologies/nesbot"
  url "https://github.com/NesloTechnologies/homebrew-nesbot/releases/download/v1.38.5/nesbot-1.38.5-darwin-arm64.tar.gz"
  sha256 "f1d7a6a739a7dc8fbf678535cca90b865de8c5030573d53d21c7aaf799b1ac69"
  version "1.38.5"
  license "MIT"

  def install
    libexec.install Dir["*"]

    # Create a wrapper script that invokes the CLI via the system node
    # Requires Node.js >= 18 (nvm, brew node, or system install)
    (bin/"nesbot").write <<~EOS
      #!/usr/bin/env bash
      exec node "#{libexec}/bin/nesbot.js" "$@"
    EOS
  end

  # No test do block — Homebrew uses PTY to spawn the test subprocess;
  # PTY allocation fails on macOS Sequoia sandbox ("can't get Master/Slave
  # device") regardless of what the test does. Correctness is verified by
  # the release artifact checksum + scripts/verify-release.sh.
end
